language: python
python:
- '2.7'
cache: apt
install:
- pip install -r requirements.txt
- pelican-themes -i pure
- sudo apt-get update
- sudo apt-get install optipng libjpeg-progs wget coreutils
script: make publish
before_deploy: cd output && ../deploy/simple-sync.py
deploy:
  provider: s3
  access_key_id: AKIAICC7Z3GSB5QRCTKA
  secret_access_key:
    secure: d9VJXcSahW+OjUxKyHEM/TE4BGjfq2NAAY2XP8e6MbfwEVOjquJDk5hHu8y8Mjh2UHP2AWMPhUmaSEluWoTc3Vc85FcKegLwj5VB3iF0UH8ykM3pBLdptpc63oFFuKo3BeyU1tWdGj0iHK557MMvhUWc6og27pcrLQo340qsgD0=
  skip_cleanup: true
  local-dir: output
  bucket: jessek.co.nz
  region: ap-southeast-2
  endpoint: jessek.co.nz.s3-website-ap-southeast-2.amazonaws.com
  detect_encoding: true
