title: jessek
description: >- 
  Collection of blog posts on linux tips and software engineering.
url: "http://jessek.co.nz"
twitter_username: jkrshw
github_username:  jkrshw
disqus: jessek

paginate: 5

# Build settings
theme: jekyll-theme-hydejack
plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-include-cache

accent_image: /images/cover.jpg
accent_color: rgb(79,177,186)

hydejack:
  cookies_banner:      true

menu:
  - title:             Archives
    url:               /archives.html

defaults:
  - scope:
      type: posts
    values:
      comments: true
  - scope:
      path:            images/
    values:
      sitemap:         false

collections:
  posts:
    output: true
    permalink: /:year/:month/:slug:output_ext
